# Even Fibonacci numbers
#
# Each new term in the Fibonacci sequence is generated by added the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed 
# four million, find the sum of the even-valued terms.

class Fib

  def fibonacci
    fib_array = [1, 2]
    i = 0
    loop do
      next_fib = fib_array[i] + fib_array[i+1]
      break if next_fib > 4000000
      fib_array.push(next_fib)
      i += 1
    end
    fib_array
  end

  def even_fibs
    fib_array = fibonacci
    fib_array.delete_if { |n| n.odd? }.inject(:+)
  end

end
